[package]
name = "fhe-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
bincode = "1.3.3"
tfhe = { version = "0.7.2", features = [ "boolean", "shortint", "integer", "x86_64-unix" ] }